import type { PublicListing } from './listing-types';

const now = Date.now();
const day = 86400000;

export const publicListings: PublicListing[] = [
  {
    id: 'PL-001',
    title: 'Casa Moderna en Guaynabo — Vista Panorámica',
    slug: 'casa-moderna-guaynabo',
    description: 'Hermosa casa renovada con acabados modernos en una de las urbanizaciones más exclusivas de Guaynabo. Amplias áreas sociales, cocina gourmet y terraza con vista panorámica a la ciudad.',
    price: 285000,
    priceLabel: '$285,000',
    operationType: 'sale',
    propertyCategory: 'residential',
    propertyType: 'Casa',
    address: 'Calle Los Filtros #42, Urb. Garden Hills',
    municipality: 'Guaynabo',
    sector: 'Garden Hills',
    region: 'Metro',
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    area: 2200,
    areaUnit: 'sq ft',
    yearBuilt: 2018,
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a1', attributeId: 'gen-renovated', active: true, featured: true, order: 1 },
      { id: 'a2', attributeId: 'gen-gated', active: true, featured: true, order: 2 },
      { id: 'a3', attributeId: 'gen-smart-home', active: true, featured: false, order: 3 },
      { id: 'a4', attributeId: 'gen-high-ceilings', active: true, featured: false, order: 4 },
      { id: 'a5', attributeId: 'gen-natural-light', active: true, featured: true, order: 5 },
      { id: 'a6', attributeId: 'gen-walk-in-closet', active: true, featured: false, order: 6 },
      { id: 'a7', attributeId: 'res-pool', active: true, featured: true, order: 7 },
      { id: 'a8', attributeId: 'res-garden', active: true, featured: false, order: 8 },
      { id: 'a9', attributeId: 'res-parking', active: true, featured: false, order: 9 },
      { id: 'a10', attributeId: 'res-cctv', active: true, featured: false, order: 10 },
    ],
    inclusions: [
      { id: 'i1', label: 'Cocina remodelada con electrodomésticos', iconName: 'CookingPot', custom: false },
      { id: 'i2', label: 'Sistema de paneles solares', iconName: 'SunMedium', custom: false },
      { id: 'i3', label: 'Cisterna 600 galones', iconName: 'Container', custom: false },
      { id: 'i4', label: 'Generador automático', iconName: 'BatteryCharging', custom: false },
      { id: 'i5', label: 'Todos los A/C instalados', iconName: 'AirVent', custom: false },
    ],
    exclusions: [
      { id: 'e1', label: 'Muebles no incluidos', iconName: 'Sofa', custom: false },
      { id: 'e2', label: 'Lavadora/secadora no incluida', iconName: 'WashingMachine', custom: false },
    ],
    rules: [],
    conditions: [
      { id: 'c1', label: 'Requiere pre-aprobación hipotecaria', type: 'requirement' },
      { id: 'c2', label: 'Cierre en 45-60 días', type: 'info' },
    ],
    idealFit: [
      { id: 'if1', profileKey: 'large-family', label: 'Ideal para familia grande', description: 'Múltiples habitaciones y áreas comunes amplias', iconName: 'UsersRound' },
      { id: 'if2', profileKey: 'professional', label: 'Ideal para profesional', description: 'Ubicación céntrica, moderno y funcional', iconName: 'Briefcase' },
    ],
    utilities: [
      { id: 'u1', attributeId: 'util-water', included: true },
      { id: 'u2', attributeId: 'util-electricity', included: true },
      { id: 'u3', attributeId: 'util-internet', included: true },
      { id: 'u4', attributeId: 'util-solar', included: true },
      { id: 'u5', attributeId: 'util-generator', included: true },
      { id: 'u6', attributeId: 'util-security-system', included: true },
    ],
    appliances: [
      { id: 'ap1', attributeId: 'app-stove', included: true, condition: 'Nueva' },
      { id: 'ap2', attributeId: 'app-fridge', included: true, condition: 'Nueva' },
      { id: 'ap3', attributeId: 'app-ac', included: true, condition: 'Nueva' },
      { id: 'ap4', attributeId: 'app-water-heater', included: true },
      { id: 'ap5', attributeId: 'app-ceiling-fans', included: true },
    ],
    restrictions: [],
    attributeGroups: [
      { id: 'ag1', label: 'Características Principales', category: 'general', attributes: ['gen-renovated', 'gen-gated', 'gen-smart-home', 'gen-high-ceilings', 'gen-natural-light'], order: 1, visible: true },
      { id: 'ag2', label: 'Amenidades', category: 'residential-amenities', attributes: ['res-pool', 'res-garden', 'res-parking', 'res-cctv'], order: 2, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'comenzar-precalificacion'],
      formMapping: {
        'solicitar-info': 'sales',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'general',
      },
    },
    formConfig: {
      formType: 'sales',
      heading: 'Solicitar información de compra',
      subheading: 'Complete el formulario y un asesor le contactará en menos de 24 horas.',
      submitLabel: 'Enviar solicitud de compra',
      successTitle: '¡Solicitud recibida!',
      successMessage: 'Un asesor de ventas le contactará pronto para coordinar los próximos pasos.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: Juan Pérez', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'juan@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'financingMethod', label: 'Método de financiamiento', type: 'select', required: true, options: [
          { value: 'cash', label: 'Cash / Efectivo' },
          { value: 'conventional', label: 'Hipoteca convencional' },
          { value: 'fha', label: 'FHA' },
          { value: 'va', label: 'VA' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'prequalified', label: '¿Tiene pre-aprobación?', type: 'select', required: false, options: [
          { value: 'yes', label: 'Sí' },
          { value: 'no', label: 'No' },
          { value: 'in-process', label: 'En proceso' },
        ]},
        { name: 'timeline', label: '¿Cuándo desea comprar?', type: 'select', required: false, options: [
          { value: 'immediate', label: 'Inmediatamente' },
          { value: '1-3months', label: '1-3 meses' },
          { value: '3-6months', label: '3-6 meses' },
          { value: 'exploring', label: 'Solo explorando' },
        ]},
        { name: 'budget', label: 'Presupuesto máximo', type: 'text', placeholder: '$000,000', required: false },
        { name: 'message', label: 'Mensaje adicional', type: 'textarea', placeholder: 'Cuéntenos sobre sus necesidades...', required: false },
      ],
    },
    featured: true,
    status: 'active',
    createdAt: new Date(now - 10 * day).toISOString(),
    updatedAt: new Date(now - 2 * day).toISOString(),
  },

  {
    id: 'PL-002',
    title: 'Apartamento en Alquiler — Condado, San Juan',
    slug: 'apartamento-condado-san-juan',
    description: 'Moderno apartamento amueblado en el corazón del Condado. A pasos de la playa, restaurantes y centros comerciales. Ideal para profesionales o parejas.',
    price: 1800,
    priceLabel: '$1,800/mes',
    operationType: 'rental',
    propertyCategory: 'residential',
    propertyType: 'Apartamento',
    address: 'Ave. Ashford #1234, Condado',
    municipality: 'San Juan',
    sector: 'Condado',
    region: 'Metro',
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    area: 1100,
    areaUnit: 'sq ft',
    yearBuilt: 2020,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a11', attributeId: 'gen-furnished', active: true, featured: true, order: 1 },
      { id: 'a12', attributeId: 'gen-ocean-view', active: true, featured: true, order: 2 },
      { id: 'a13', attributeId: 'gen-accessible', active: true, featured: false, order: 3 },
      { id: 'a14', attributeId: 'res-pool', active: true, featured: true, order: 4 },
      { id: 'a15', attributeId: 'res-gym', active: true, featured: false, order: 5 },
      { id: 'a16', attributeId: 'res-elevator', active: true, featured: false, order: 6 },
      { id: 'a17', attributeId: 'res-rooftop', active: true, featured: false, order: 7 },
      { id: 'a18', attributeId: 'res-lobby', active: true, featured: false, order: 8 },
      { id: 'a19', attributeId: 'res-security-guard', active: true, featured: false, order: 9 },
      { id: 'a20', attributeId: 'res-parking', active: true, featured: false, order: 10 },
    ],
    inclusions: [
      { id: 'i6', label: 'Muebles completos', iconName: 'Sofa', custom: false },
      { id: 'i7', label: 'Agua incluida', iconName: 'Droplets', custom: false },
      { id: 'i8', label: 'Internet incluido', iconName: 'Wifi', custom: false },
      { id: 'i9', label: 'Cable TV', iconName: 'Tv', custom: false },
    ],
    exclusions: [
      { id: 'e3', label: 'Electricidad no incluida', iconName: 'Zap', custom: false },
      { id: 'e4', label: 'Gas no incluido', iconName: 'Flame', custom: false },
    ],
    rules: [
      { id: 'r1', label: 'No mascotas', type: 'restricted' },
      { id: 'r2', label: 'No fumadores', type: 'restricted' },
      { id: 'r3', label: 'Contrato mínimo 12 meses', type: 'info' },
      { id: 'r4', label: 'No subarrendar', type: 'restricted' },
      { id: 'r5', label: 'Máximo 2 ocupantes', type: 'info' },
    ],
    conditions: [
      { id: 'c3', label: 'Depósito: primer y último mes', type: 'requirement' },
      { id: 'c4', label: 'Verificación de crédito obligatoria', type: 'requirement' },
      { id: 'c5', label: 'Prueba de ingresos 3x renta', type: 'requirement' },
    ],
    idealFit: [
      { id: 'if3', profileKey: 'professional', label: 'Ideal para profesional', description: 'Ubicación céntrica, moderno y funcional', iconName: 'Briefcase' },
      { id: 'if4', profileKey: 'airbnb', label: 'Ideal para Airbnb', description: 'Alta demanda turística y buen retorno', iconName: 'Plane' },
    ],
    utilities: [
      { id: 'u7', attributeId: 'util-water', included: true, details: 'Incluida en renta' },
      { id: 'u8', attributeId: 'util-electricity', included: false, details: 'Cuenta separada LUMA' },
      { id: 'u9', attributeId: 'util-internet', included: true, details: 'Fibra 300mbps incluida' },
    ],
    appliances: [
      { id: 'ap6', attributeId: 'app-stove', included: true },
      { id: 'ap7', attributeId: 'app-fridge', included: true },
      { id: 'ap8', attributeId: 'app-washer', included: true },
      { id: 'ap9', attributeId: 'app-dryer', included: true },
      { id: 'ap10', attributeId: 'app-ac', included: true },
      { id: 'ap11', attributeId: 'app-microwave', included: true },
    ],
    restrictions: [
      { id: 'rest1', label: 'No se permiten modificaciones estructurales', severity: 'hard' },
      { id: 'rest2', label: 'Horario de mudanza: 8am-6pm L-S', severity: 'soft' },
    ],
    attributeGroups: [
      { id: 'ag3', label: 'Características', category: 'general', attributes: ['gen-furnished', 'gen-ocean-view', 'gen-accessible'], order: 1, visible: true },
      { id: 'ag4', label: 'Amenidades del Edificio', category: 'residential-amenities', attributes: ['res-pool', 'res-gym', 'res-elevator', 'res-rooftop', 'res-lobby', 'res-security-guard'], order: 2, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'aplicar-alquiler',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'ver-requisitos'],
      formMapping: {
        'solicitar-info': 'rental',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'general',
      },
    },
    formConfig: {
      formType: 'rental',
      heading: 'Aplicar para alquiler',
      subheading: 'Complete la solicitud y le contactaremos para coordinar una visita.',
      submitLabel: 'Enviar solicitud de alquiler',
      successTitle: '¡Solicitud enviada!',
      successMessage: 'Revisaremos su solicitud y le contactaremos en las próximas 48 horas.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: María López', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'maria@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'moveInDate', label: 'Fecha deseada de mudanza', type: 'date', required: true },
        { name: 'occupants', label: 'Número de ocupantes', type: 'number', placeholder: '2', required: true },
        { name: 'pets', label: '¿Tiene mascotas?', type: 'select', required: true, options: [
          { value: 'no', label: 'No' },
          { value: 'dog', label: 'Sí — Perro' },
          { value: 'cat', label: 'Sí — Gato' },
          { value: 'other', label: 'Sí — Otro' },
        ]},
        { name: 'incomeSource', label: 'Fuente de ingresos', type: 'select', required: true, options: [
          { value: 'employment', label: 'Empleo' },
          { value: 'self-employed', label: 'Cuenta propia' },
          { value: 'retirement', label: 'Retiro / Pensión' },
          { value: 'section8', label: 'Section 8' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'rentalDuration', label: 'Duración deseada', type: 'select', required: false, options: [
          { value: '6months', label: '6 meses' },
          { value: '12months', label: '12 meses' },
          { value: '24months', label: '24 meses' },
          { value: 'flexible', label: 'Flexible' },
        ]},
        { name: 'message', label: 'Información adicional', type: 'textarea', placeholder: 'Cuéntenos sobre usted...', required: false },
      ],
    },
    featured: true,
    status: 'active',
    createdAt: new Date(now - 7 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
  },

  {
    id: 'PL-003',
    title: 'Local Comercial en Ponce Centro',
    slug: 'local-comercial-ponce',
    description: 'Amplio local comercial en el corazón de Ponce. Ideal para retail, restaurante o oficina. Alto tráfico peatonal y vehicular. Estacionamiento disponible.',
    price: 195000,
    priceLabel: '$195,000',
    operationType: 'sale',
    propertyCategory: 'commercial',
    propertyType: 'Local Comercial',
    address: 'Calle Mayor #88, Ponce Centro',
    municipality: 'Ponce',
    sector: 'Centro',
    region: 'Sur',
    bedrooms: undefined,
    bathrooms: 2,
    parkingSpaces: 6,
    area: 3500,
    areaUnit: 'sq ft',
    yearBuilt: 1985,
    photos: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a21', attributeId: 'com-parking-lot', active: true, featured: true, order: 1 },
      { id: 'a22', attributeId: 'com-high-traffic', active: true, featured: true, order: 2 },
      { id: 'a23', attributeId: 'com-loading-dock', active: true, featured: false, order: 3 },
      { id: 'a24', attributeId: 'com-subdivisible', active: true, featured: true, order: 4 },
      { id: 'a25', attributeId: 'com-ada-compliant', active: true, featured: false, order: 5 },
      { id: 'a26', attributeId: 'com-hvac', active: true, featured: false, order: 6 },
      { id: 'a27', attributeId: 'com-fire-system', active: true, featured: false, order: 7 },
      { id: 'a28', attributeId: 'com-signage', active: true, featured: false, order: 8 },
    ],
    inclusions: [
      { id: 'i10', label: 'HVAC central instalado', iconName: 'AirVent', custom: false },
      { id: 'i11', label: 'Sistema contra incendios', iconName: 'Flame', custom: false },
      { id: 'i12', label: '6 espacios de estacionamiento', iconName: 'ParkingCircle', custom: false },
    ],
    exclusions: [
      { id: 'e5', label: 'Sin equipo de cocina', iconName: 'CookingPot', custom: false },
      { id: 'e6', label: 'Sin mobiliario', iconName: 'Sofa', custom: false },
    ],
    rules: [],
    conditions: [
      { id: 'c6', label: 'Inspección comercial requerida', type: 'requirement' },
      { id: 'c7', label: 'Permisos de uso comercial al día', type: 'info' },
      { id: 'c8', label: 'Sujeto a aprobación de zonificación para cambio de uso', type: 'warning' },
    ],
    idealFit: [
      { id: 'if5', profileKey: 'commercial-business', label: 'Ideal para negocio', description: 'Visibilidad, tráfico y espacio comercial', iconName: 'Store' },
      { id: 'if6', profileKey: 'investment', label: 'Ideal para inversión', description: 'Alto potencial de retorno y valorización', iconName: 'TrendingUp' },
    ],
    utilities: [
      { id: 'u10', attributeId: 'util-water', included: true },
      { id: 'u11', attributeId: 'util-electricity', included: true },
      { id: 'u12', attributeId: 'util-internet', included: true },
    ],
    appliances: [],
    restrictions: [],
    attributeGroups: [
      { id: 'ag5', label: 'Características Comerciales', category: 'commercial', attributes: ['com-parking-lot', 'com-high-traffic', 'com-loading-dock', 'com-subdivisible', 'com-ada-compliant'], order: 1, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'hablar-asesor', 'whatsapp'],
      formMapping: {
        'solicitar-info': 'commercial',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'commercial',
      },
    },
    formConfig: {
      formType: 'commercial',
      heading: 'Consulta comercial',
      subheading: 'Déjenos saber su interés y un asesor comercial le contactará.',
      submitLabel: 'Enviar consulta comercial',
      successTitle: '¡Consulta recibida!',
      successMessage: 'Nuestro equipo comercial revisará su solicitud y le contactará pronto.',
      fields: [
        { name: 'name', label: 'Nombre / Empresa', type: 'text', placeholder: 'Ej: Empresa ABC', required: true },
        { name: 'email', label: 'Email corporativo', type: 'email', placeholder: 'contacto@empresa.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'businessType', label: 'Tipo de negocio', type: 'select', required: true, options: [
          { value: 'retail', label: 'Retail / Tienda' },
          { value: 'restaurant', label: 'Restaurante / Cafetería' },
          { value: 'office', label: 'Oficina' },
          { value: 'warehouse', label: 'Almacén' },
          { value: 'medical', label: 'Consultorio / Clínica' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'teamSize', label: 'Tamaño del equipo', type: 'number', placeholder: '10', required: false },
        { name: 'occupancyDate', label: 'Fecha estimada de ocupación', type: 'date', required: false },
        { name: 'message', label: 'Detalles del proyecto', type: 'textarea', placeholder: 'Describa su negocio y necesidades...', required: false },
      ],
    },
    featured: false,
    status: 'active',
    createdAt: new Date(now - 15 * day).toISOString(),
    updatedAt: new Date(now - 3 * day).toISOString(),
  },

  {
    id: 'PL-004',
    title: 'Oficina para Alquiler — Hato Rey',
    slug: 'oficina-hato-rey',
    description: 'Espacio de oficina moderno en el distrito financiero de Hato Rey. Edificio clase A con todas las amenidades corporativas.',
    price: 3500,
    priceLabel: '$3,500/mes',
    operationType: 'rental',
    propertyCategory: 'commercial',
    propertyType: 'Oficina',
    address: 'Ave. Muñoz Rivera #500, Torre Financiera',
    municipality: 'San Juan',
    sector: 'Hato Rey',
    region: 'Metro',
    bedrooms: undefined,
    bathrooms: 3,
    parkingSpaces: 4,
    area: 2000,
    areaUnit: 'sq ft',
    yearBuilt: 2010,
    photos: [
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a29', attributeId: 'com-parking-lot', active: true, featured: true, order: 1 },
      { id: 'a30', attributeId: 'com-office-ready', active: true, featured: true, order: 2 },
      { id: 'a31', attributeId: 'com-hvac', active: true, featured: false, order: 3 },
      { id: 'a32', attributeId: 'com-ada-compliant', active: true, featured: false, order: 4 },
      { id: 'a33', attributeId: 'res-elevator', active: true, featured: false, order: 5 },
      { id: 'a34', attributeId: 'res-lobby', active: true, featured: false, order: 6 },
      { id: 'a35', attributeId: 'res-security-guard', active: true, featured: false, order: 7 },
    ],
    inclusions: [
      { id: 'i13', label: 'HVAC central', iconName: 'AirVent', custom: false },
      { id: 'i14', label: 'Internet fibra óptica', iconName: 'Wifi', custom: false },
      { id: 'i15', label: 'Seguridad 24/7', iconName: 'ShieldCheck', custom: false },
      { id: 'i16', label: '4 espacios de parking', iconName: 'ParkingCircle', custom: false },
    ],
    exclusions: [
      { id: 'e7', label: 'Mobiliario no incluido', iconName: 'Sofa', custom: false },
      { id: 'e8', label: 'Servicio de limpieza no incluido', iconName: 'Sparkles', custom: false },
    ],
    rules: [
      { id: 'r6', label: 'Horario de acceso: 6am-11pm', type: 'info' },
      { id: 'r7', label: 'No se permiten actividades industriales', type: 'restricted' },
      { id: 'r8', label: 'Contrato mínimo 24 meses', type: 'info' },
    ],
    conditions: [
      { id: 'c9', label: 'Depósito de 3 meses', type: 'requirement' },
      { id: 'c10', label: 'Seguro de responsabilidad requerido', type: 'requirement' },
    ],
    idealFit: [
      { id: 'if7', profileKey: 'commercial-business', label: 'Ideal para negocio', description: 'Visibilidad, tráfico y espacio comercial', iconName: 'Store' },
      { id: 'if8', profileKey: 'professional', label: 'Ideal para profesional', description: 'Ubicación céntrica, moderno y funcional', iconName: 'Briefcase' },
    ],
    utilities: [
      { id: 'u13', attributeId: 'util-water', included: true },
      { id: 'u14', attributeId: 'util-electricity', included: false },
      { id: 'u15', attributeId: 'util-internet', included: true },
    ],
    appliances: [],
    restrictions: [],
    attributeGroups: [
      { id: 'ag6', label: 'Facilidades del Edificio', category: 'commercial', attributes: ['com-parking-lot', 'com-office-ready', 'com-hvac', 'com-ada-compliant'], order: 1, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'hablar-asesor'],
      formMapping: {
        'solicitar-info': 'commercial',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'commercial',
      },
    },
    formConfig: {
      formType: 'commercial',
      heading: 'Consulta de alquiler comercial',
      subheading: 'Solicite información sobre este espacio de oficina.',
      submitLabel: 'Enviar solicitud',
      successTitle: '¡Solicitud recibida!',
      successMessage: 'Nuestro equipo comercial le contactará para coordinar una visita.',
      fields: [
        { name: 'name', label: 'Nombre / Empresa', type: 'text', placeholder: 'Ej: Tech Corp', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'contacto@empresa.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'businessType', label: 'Tipo de negocio', type: 'select', required: true, options: [
          { value: 'legal', label: 'Legal / Abogados' },
          { value: 'accounting', label: 'Contabilidad' },
          { value: 'tech', label: 'Tecnología' },
          { value: 'consulting', label: 'Consultoría' },
          { value: 'medical', label: 'Médico / Salud' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'teamSize', label: 'Empleados', type: 'number', placeholder: '15', required: false },
        { name: 'occupancyDate', label: 'Fecha de inicio', type: 'date', required: false },
        { name: 'message', label: 'Requisitos adicionales', type: 'textarea', placeholder: 'Describa sus necesidades...', required: false },
      ],
    },
    featured: false,
    status: 'active',
    createdAt: new Date(now - 12 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
  },

  {
    id: 'PL-005',
    title: 'Multifamiliar — 4 Unidades en Carolina',
    slug: 'multifamiliar-carolina',
    description: 'Propiedad multifamiliar de 4 unidades con excelente retorno de inversión. Todas las unidades alquiladas con inquilinos estables. Ideal para inversionista.',
    price: 320000,
    priceLabel: '$320,000',
    operationType: 'sale',
    propertyCategory: 'residential',
    propertyType: 'Multifamiliar',
    address: 'Calle 3 #15, Urb. Valle Arriba',
    municipality: 'Carolina',
    sector: 'Valle Arriba',
    region: 'Metro',
    bedrooms: 8,
    bathrooms: 4,
    parkingSpaces: 4,
    area: 4800,
    areaUnit: 'sq ft',
    yearBuilt: 1995,
    photos: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a36', attributeId: 'gen-renovated', active: true, featured: true, order: 1 },
      { id: 'a37', attributeId: 'res-parking', active: true, featured: true, order: 2 },
      { id: 'a38', attributeId: 'res-garden', active: true, featured: false, order: 3 },
      { id: 'a39', attributeId: 'gen-laundry-room', active: true, featured: false, order: 4 },
      { id: 'a40', attributeId: 'res-cctv', active: true, featured: false, order: 5 },
      { id: 'a41', attributeId: 'gen-storage', active: true, featured: false, order: 6 },
    ],
    inclusions: [
      { id: 'i17', label: 'Todas las unidades alquiladas', iconName: 'Users', custom: true },
      { id: 'i18', label: 'Ingreso mensual: $4,800', iconName: 'DollarSign', custom: true },
      { id: 'i19', label: 'Contratos vigentes transferibles', iconName: 'FileText', custom: true },
      { id: 'i20', label: 'Techo nuevo (2023)', iconName: 'Home', custom: true },
    ],
    exclusions: [
      { id: 'e9', label: 'No incluye electrodomésticos de unidades', iconName: 'Refrigerator', custom: false },
    ],
    rules: [],
    conditions: [
      { id: 'c11', label: 'Venta sujeta a asignación de contratos', type: 'info' },
      { id: 'c12', label: 'Inspección con cita previa (unidades ocupadas)', type: 'requirement' },
      { id: 'c13', label: 'Se prefiere comprador con experiencia en multifamiliar', type: 'info' },
    ],
    idealFit: [
      { id: 'if9', profileKey: 'investment', label: 'Ideal para inversión', description: 'Alto potencial de retorno y valorización', iconName: 'TrendingUp' },
      { id: 'if10', profileKey: 'airbnb', label: 'Ideal para Airbnb', description: 'Alta demanda turística y buen retorno', iconName: 'Plane' },
    ],
    utilities: [
      { id: 'u16', attributeId: 'util-water', included: true },
      { id: 'u17', attributeId: 'util-electricity', included: true },
      { id: 'u18', attributeId: 'util-cistern', included: true },
    ],
    appliances: [],
    restrictions: [],
    attributeGroups: [
      { id: 'ag7', label: 'Detalles de Inversión', category: 'general', attributes: ['gen-renovated'], order: 1, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'hablar-asesor'],
      formMapping: {
        'solicitar-info': 'investor',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'investor',
      },
    },
    formConfig: {
      formType: 'investor',
      heading: 'Consulta de inversión',
      subheading: 'Solicite información detallada sobre esta oportunidad de inversión.',
      submitLabel: 'Solicitar información de inversión',
      successTitle: '¡Consulta de inversión recibida!',
      successMessage: 'Un asesor especializado en inversiones le contactará con los detalles financieros.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: Pedro Morales', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'pedro@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'investmentExperience', label: 'Experiencia en inversiones', type: 'select', required: true, options: [
          { value: 'first-time', label: 'Primera inversión' },
          { value: '1-3', label: '1-3 propiedades' },
          { value: '4-10', label: '4-10 propiedades' },
          { value: '10+', label: 'Más de 10 propiedades' },
        ]},
        { name: 'financingMethod', label: 'Método de financiamiento', type: 'select', required: true, options: [
          { value: 'cash', label: 'Cash' },
          { value: 'conventional', label: 'Hipoteca convencional' },
          { value: 'portfolio', label: 'Préstamo de portafolio' },
          { value: 'hard-money', label: 'Hard money' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'timeline', label: 'Timeline de compra', type: 'select', required: false, options: [
          { value: 'immediate', label: 'Inmediato' },
          { value: '30days', label: '30 días' },
          { value: '60days', label: '60 días' },
          { value: 'exploring', label: 'Explorando' },
        ]},
        { name: 'message', label: 'Comentarios', type: 'textarea', placeholder: 'Cuéntenos sobre su estrategia de inversión...', required: false },
      ],
    },
    featured: true,
    status: 'active',
    createdAt: new Date(now - 5 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
  },

  {
    id: 'PL-006',
    title: 'Terreno Residencial — 1 Cuerda en Rincón',
    slug: 'terreno-rincon',
    description: 'Hermoso solar de 1 cuerda en Rincón con vista al mar. Zonificado residencial, acceso pavimentado, agua y electricidad disponibles. Listo para construir.',
    price: 89000,
    priceLabel: '$89,000',
    operationType: 'sale',
    propertyCategory: 'land',
    propertyType: 'Terreno',
    address: 'Bo. Pueblo, Sector Playa',
    municipality: 'Rincón',
    sector: 'Barrio Pueblo',
    region: 'Oeste',
    bedrooms: undefined,
    bathrooms: undefined,
    parkingSpaces: undefined,
    area: 3930,
    areaUnit: 'sq m',
    yearBuilt: undefined,
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a42', attributeId: 'land-flat', active: true, featured: true, order: 1 },
      { id: 'a43', attributeId: 'land-paved-access', active: true, featured: true, order: 2 },
      { id: 'a44', attributeId: 'land-zoned-residential', active: true, featured: true, order: 3 },
      { id: 'a45', attributeId: 'land-water-access', active: true, featured: false, order: 4 },
      { id: 'a46', attributeId: 'land-electricity-nearby', active: true, featured: false, order: 5 },
      { id: 'a47', attributeId: 'land-fenced', active: true, featured: false, order: 6 },
      { id: 'a48', attributeId: 'land-cleared', active: true, featured: false, order: 7 },
      { id: 'a49', attributeId: 'gen-ocean-view', active: true, featured: true, order: 8 },
    ],
    inclusions: [
      { id: 'i21', label: 'Acceso a agua AAA', iconName: 'Droplets', custom: false },
      { id: 'i22', label: 'Poste de luz LUMA cercano', iconName: 'Zap', custom: false },
      { id: 'i23', label: 'Deslinde completado', iconName: 'MapPin', custom: true },
      { id: 'i24', label: 'Permisos de uso al día', iconName: 'FileCheck', custom: true },
    ],
    exclusions: [],
    rules: [],
    conditions: [
      { id: 'c14', label: 'Requiere verificación de zonificación antes de construcción', type: 'info' },
      { id: 'c15', label: 'No tiene estructura existente', type: 'info' },
    ],
    idealFit: [
      { id: 'if11', profileKey: 'developer', label: 'Ideal para desarrollador', description: 'Terreno amplio con potencial de desarrollo', iconName: 'Hammer' },
      { id: 'if12', profileKey: 'retiree', label: 'Ideal para retiro', description: 'Tranquilo, accesible y bajo mantenimiento', iconName: 'Armchair' },
      { id: 'if13', profileKey: 'investment', label: 'Ideal para inversión', description: 'Alto potencial de retorno y valorización', iconName: 'TrendingUp' },
    ],
    utilities: [],
    appliances: [],
    restrictions: [],
    attributeGroups: [
      { id: 'ag8', label: 'Características del Terreno', category: 'land', attributes: ['land-flat', 'land-paved-access', 'land-zoned-residential', 'land-water-access', 'land-electricity-nearby', 'land-fenced', 'land-cleared'], order: 1, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'whatsapp'],
      formMapping: {
        'solicitar-info': 'sales',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'general',
      },
    },
    formConfig: {
      formType: 'sales',
      heading: 'Información sobre este terreno',
      subheading: 'Complete el formulario para recibir los detalles completos del solar.',
      submitLabel: 'Solicitar información',
      successTitle: '¡Solicitud recibida!',
      successMessage: 'Le enviaremos los documentos del terreno y coordinaremos una visita.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: Roberto Hernández', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'roberto@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'purpose', label: '¿Para qué usaría el terreno?', type: 'select', required: true, options: [
          { value: 'build-home', label: 'Construir residencia' },
          { value: 'investment', label: 'Inversión' },
          { value: 'agriculture', label: 'Uso agrícola' },
          { value: 'development', label: 'Desarrollo' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'timeline', label: '¿Cuándo planea comprar?', type: 'select', required: false, options: [
          { value: 'immediate', label: 'Inmediatamente' },
          { value: '1-3months', label: '1-3 meses' },
          { value: '3-6months', label: '3-6 meses' },
          { value: 'exploring', label: 'Solo explorando' },
        ]},
        { name: 'message', label: 'Mensaje', type: 'textarea', placeholder: 'Cuéntenos sobre su proyecto...', required: false },
      ],
    },
    featured: false,
    status: 'active',
    createdAt: new Date(now - 20 * day).toISOString(),
    updatedAt: new Date(now - 5 * day).toISOString(),
  },

  {
    id: 'PL-007',
    title: 'Casa de Playa — Remodelada en Luquillo',
    slug: 'casa-playa-luquillo',
    description: 'Encantadora casa de playa completamente remodelada a minutos de la playa de Luquillo. Perfecta para vivir o como inversión de alquiler vacacional.',
    price: 215000,
    priceLabel: '$215,000',
    operationType: 'sale',
    propertyCategory: 'residential',
    propertyType: 'Casa',
    address: 'Calle Mar Azul #7, Bo. Fortuna',
    municipality: 'Luquillo',
    sector: 'Fortuna',
    region: 'Este',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    area: 1600,
    areaUnit: 'sq ft',
    yearBuilt: 2005,
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a50', attributeId: 'gen-renovated', active: true, featured: true, order: 1 },
      { id: 'a51', attributeId: 'gen-ocean-view', active: true, featured: true, order: 2 },
      { id: 'a52', attributeId: 'gen-pet-friendly', active: true, featured: false, order: 3 },
      { id: 'a53', attributeId: 'gen-natural-light', active: true, featured: true, order: 4 },
      { id: 'a54', attributeId: 'res-balcony', active: true, featured: false, order: 5 },
      { id: 'a55', attributeId: 'res-garden', active: true, featured: false, order: 6 },
      { id: 'a56', attributeId: 'res-bbq', active: true, featured: false, order: 7 },
      { id: 'a57', attributeId: 'res-parking', active: true, featured: false, order: 8 },
    ],
    inclusions: [
      { id: 'i25', label: 'Paneles solares (10kW)', iconName: 'SunMedium', custom: false },
      { id: 'i26', label: 'Cisterna 400 galones', iconName: 'Container', custom: false },
      { id: 'i27', label: 'Todos los electrodomésticos', iconName: 'Refrigerator', custom: false },
      { id: 'i28', label: 'Muebles de terraza', iconName: 'Armchair', custom: true },
    ],
    exclusions: [
      { id: 'e10', label: 'Muebles interiores no incluidos', iconName: 'Sofa', custom: false },
    ],
    rules: [],
    conditions: [
      { id: 'c16', label: 'Zona de inundación — seguro especial requerido', type: 'warning' },
      { id: 'c17', label: 'Cierre en 30-45 días', type: 'info' },
    ],
    idealFit: [
      { id: 'if14', profileKey: 'retiree', label: 'Ideal para retiro', description: 'Tranquilo, accesible y bajo mantenimiento', iconName: 'Armchair' },
      { id: 'if15', profileKey: 'airbnb', label: 'Ideal para Airbnb', description: 'Alta demanda turística y buen retorno', iconName: 'Plane' },
      { id: 'if16', profileKey: 'small-family', label: 'Ideal para familia pequeña', description: 'Espacios cómodos para familias de 2-4 personas', iconName: 'Users' },
    ],
    utilities: [
      { id: 'u19', attributeId: 'util-water', included: true },
      { id: 'u20', attributeId: 'util-electricity', included: true },
      { id: 'u21', attributeId: 'util-solar', included: true },
      { id: 'u22', attributeId: 'util-cistern', included: true },
      { id: 'u23', attributeId: 'util-internet', included: true },
    ],
    appliances: [
      { id: 'ap12', attributeId: 'app-stove', included: true },
      { id: 'ap13', attributeId: 'app-fridge', included: true },
      { id: 'ap14', attributeId: 'app-washer', included: true },
      { id: 'ap15', attributeId: 'app-ac', included: true },
      { id: 'ap16', attributeId: 'app-water-heater', included: true },
      { id: 'ap17', attributeId: 'app-ceiling-fans', included: true },
    ],
    restrictions: [],
    attributeGroups: [
      { id: 'ag9', label: 'Características', category: 'general', attributes: ['gen-renovated', 'gen-ocean-view', 'gen-pet-friendly', 'gen-natural-light'], order: 1, visible: true },
      { id: 'ag10', label: 'Exterior', category: 'residential-amenities', attributes: ['res-balcony', 'res-garden', 'res-bbq', 'res-parking'], order: 2, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'solicitar-info',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'comenzar-precalificacion'],
      formMapping: {
        'solicitar-info': 'sales',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'general',
      },
    },
    formConfig: {
      formType: 'sales',
      heading: 'Solicitar información',
      subheading: 'Complete el formulario para recibir todos los detalles de esta propiedad.',
      submitLabel: 'Enviar solicitud',
      successTitle: '¡Solicitud recibida!',
      successMessage: 'Un asesor le contactará pronto con información detallada.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: Ana Martínez', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'ana@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'financingMethod', label: 'Método de financiamiento', type: 'select', required: true, options: [
          { value: 'cash', label: 'Cash' },
          { value: 'conventional', label: 'Hipoteca convencional' },
          { value: 'fha', label: 'FHA' },
          { value: 'va', label: 'VA' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'prequalified', label: '¿Tiene pre-aprobación?', type: 'select', required: false, options: [
          { value: 'yes', label: 'Sí' },
          { value: 'no', label: 'No' },
          { value: 'in-process', label: 'En proceso' },
        ]},
        { name: 'timeline', label: '¿Cuándo desea comprar?', type: 'select', required: false, options: [
          { value: 'immediate', label: 'Inmediatamente' },
          { value: '1-3months', label: '1-3 meses' },
          { value: '3-6months', label: '3-6 meses' },
          { value: 'exploring', label: 'Solo explorando' },
        ]},
        { name: 'message', label: 'Mensaje', type: 'textarea', placeholder: 'Cuéntenos sobre sus necesidades...', required: false },
      ],
    },
    featured: false,
    status: 'active',
    createdAt: new Date(now - 8 * day).toISOString(),
    updatedAt: new Date(now - 2 * day).toISOString(),
  },

  {
    id: 'PL-008',
    title: 'Townhouse para Alquiler — Caguas',
    slug: 'townhouse-caguas',
    description: 'Townhouse de 3 habitaciones en urbanización cerrada con piscina y áreas recreativas. Excelente para familia. Cerca de escuelas y centros comerciales.',
    price: 1200,
    priceLabel: '$1,200/mes',
    operationType: 'rental',
    propertyCategory: 'residential',
    propertyType: 'Townhouse',
    address: 'Calle 5 #22, Urb. Bairoa Park',
    municipality: 'Caguas',
    sector: 'Bairoa',
    region: 'Centro',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 1,
    area: 1400,
    areaUnit: 'sq ft',
    yearBuilt: 2012,
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      { id: 'a58', attributeId: 'gen-gated', active: true, featured: true, order: 1 },
      { id: 'a59', attributeId: 'res-pool', active: true, featured: true, order: 2 },
      { id: 'a60', attributeId: 'res-playground', active: true, featured: true, order: 3 },
      { id: 'a61', attributeId: 'res-parking', active: true, featured: false, order: 4 },
      { id: 'a62', attributeId: 'res-community-room', active: true, featured: false, order: 5 },
      { id: 'a63', attributeId: 'gen-laundry-room', active: true, featured: false, order: 6 },
      { id: 'a64', attributeId: 'res-security-guard', active: true, featured: false, order: 7 },
    ],
    inclusions: [
      { id: 'i29', label: 'Agua incluida en HOA', iconName: 'Droplets', custom: false },
      { id: 'i30', label: 'Mantenimiento de áreas comunes', iconName: 'Sparkles', custom: true },
      { id: 'i31', label: 'Acceso a piscina y áreas recreativas', iconName: 'Waves', custom: false },
    ],
    exclusions: [
      { id: 'e11', label: 'Electricidad no incluida', iconName: 'Zap', custom: false },
      { id: 'e12', label: 'Internet no incluido', iconName: 'Wifi', custom: false },
      { id: 'e13', label: 'Muebles no incluidos', iconName: 'Sofa', custom: false },
    ],
    rules: [
      { id: 'r9', label: 'Mascotas permitidas (máx. 2, hasta 30 lbs)', type: 'conditional' },
      { id: 'r10', label: 'Acepta Section 8', type: 'allowed' },
      { id: 'r11', label: 'No fumadores dentro de la unidad', type: 'restricted' },
      { id: 'r12', label: 'Contrato mínimo 12 meses', type: 'info' },
      { id: 'r13', label: 'Máximo 5 ocupantes', type: 'info' },
    ],
    conditions: [
      { id: 'c18', label: 'Depósito: 1 mes', type: 'requirement' },
      { id: 'c19', label: 'Verificación de crédito y antecedentes', type: 'requirement' },
      { id: 'c20', label: 'Prueba de ingresos 2.5x renta', type: 'requirement' },
      { id: 'c21', label: 'Se requiere referencia de dueño anterior', type: 'info' },
    ],
    idealFit: [
      { id: 'if17', profileKey: 'small-family', label: 'Ideal para familia pequeña', description: 'Espacios cómodos para familias de 2-4 personas', iconName: 'Users' },
      { id: 'if18', profileKey: 'first-time-buyer', label: 'Ideal para primer inquilino', description: 'Precio accesible y condiciones flexibles', iconName: 'Heart' },
    ],
    utilities: [
      { id: 'u24', attributeId: 'util-water', included: true, details: 'Incluida en HOA' },
      { id: 'u25', attributeId: 'util-electricity', included: false },
      { id: 'u26', attributeId: 'util-internet', included: false },
    ],
    appliances: [
      { id: 'ap18', attributeId: 'app-stove', included: true },
      { id: 'ap19', attributeId: 'app-fridge', included: true },
      { id: 'ap20', attributeId: 'app-ac', included: true },
      { id: 'ap21', attributeId: 'app-water-heater', included: true },
    ],
    restrictions: [
      { id: 'rest3', label: 'No se permiten modificaciones sin aprobación', severity: 'hard' },
      { id: 'rest4', label: 'Reglamento de HOA aplica', severity: 'soft' },
    ],
    attributeGroups: [
      { id: 'ag11', label: 'Comunidad', category: 'general', attributes: ['gen-gated'], order: 1, visible: true },
      { id: 'ag12', label: 'Amenidades', category: 'residential-amenities', attributes: ['res-pool', 'res-playground', 'res-parking', 'res-community-room', 'res-security-guard'], order: 2, visible: true },
    ],
    ctaConfig: {
      primaryCTA: 'aplicar-alquiler',
      secondaryCTAs: ['agendar-visita', 'whatsapp', 'ver-requisitos'],
      formMapping: {
        'solicitar-info': 'rental',
        'agendar-visita': 'showing',
        'aplicar-alquiler': 'rental',
        'comenzar-precalificacion': 'prequalification',
        'whatsapp': 'general',
        'ver-requisitos': 'general',
        'tour-virtual': 'general',
        'hablar-asesor': 'general',
      },
    },
    formConfig: {
      formType: 'rental',
      heading: 'Aplicar para alquiler',
      subheading: 'Complete la solicitud para ser considerado como inquilino.',
      submitLabel: 'Enviar solicitud de alquiler',
      successTitle: '¡Solicitud enviada!',
      successMessage: 'Evaluaremos su solicitud y le contactaremos en las próximas 48 horas.',
      fields: [
        { name: 'name', label: 'Nombre completo', type: 'text', placeholder: 'Ej: Carmen Díaz', required: true },
        { name: 'email', label: 'Email', type: 'email', placeholder: 'carmen@email.com', required: true },
        { name: 'phone', label: 'Teléfono', type: 'phone', placeholder: '(787) 555-0000', required: true },
        { name: 'moveInDate', label: 'Fecha deseada de mudanza', type: 'date', required: true },
        { name: 'occupants', label: 'Número de ocupantes', type: 'number', placeholder: '3', required: true },
        { name: 'pets', label: '¿Tiene mascotas?', type: 'select', required: true, options: [
          { value: 'no', label: 'No' },
          { value: 'dog-small', label: 'Sí — Perro (menos de 30 lbs)' },
          { value: 'cat', label: 'Sí — Gato' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'incomeSource', label: 'Fuente de ingresos', type: 'select', required: true, options: [
          { value: 'employment', label: 'Empleo' },
          { value: 'self-employed', label: 'Cuenta propia' },
          { value: 'retirement', label: 'Retiro / Pensión' },
          { value: 'section8', label: 'Section 8' },
          { value: 'other', label: 'Otro' },
        ]},
        { name: 'hasVoucher', label: '¿Tiene voucher Section 8?', type: 'select', required: false, options: [
          { value: 'yes', label: 'Sí' },
          { value: 'no', label: 'No' },
          { value: 'pending', label: 'En proceso' },
        ]},
        { name: 'rentalDuration', label: 'Duración deseada', type: 'select', required: false, options: [
          { value: '12months', label: '12 meses' },
          { value: '24months', label: '24 meses' },
          { value: 'flexible', label: 'Flexible' },
        ]},
        { name: 'message', label: 'Información adicional', type: 'textarea', placeholder: 'Cuéntenos sobre su familia y necesidades...', required: false },
      ],
    },
    featured: false,
    status: 'active',
    createdAt: new Date(now - 3 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
  },
];
