import * as LucideIcons from 'lucide-react';
import type { LucideProps } from 'lucide-react';

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  Home: LucideIcons.Home,
  Sofa: LucideIcons.Sofa,
  Hammer: LucideIcons.Hammer,
  HardHat: LucideIcons.HardHat,
  CornerDownRight: LucideIcons.CornerDownRight,
  Waves: LucideIcons.Waves,
  Mountain: LucideIcons.Mountain,
  ShieldCheck: LucideIcons.ShieldCheck,
  Dog: LucideIcons.Dog,
  Accessibility: LucideIcons.Accessibility,
  Smartphone: LucideIcons.Smartphone,
  Archive: LucideIcons.Archive,
  WashingMachine: LucideIcons.WashingMachine,
  DoorOpen: LucideIcons.DoorOpen,
  ArrowUpFromLine: LucideIcons.ArrowUpFromLine,
  Sun: LucideIcons.Sun,
  Droplets: LucideIcons.Droplets,
  Zap: LucideIcons.Zap,
  Wifi: LucideIcons.Wifi,
  SunMedium: LucideIcons.SunMedium,
  BatteryCharging: LucideIcons.BatteryCharging,
  Flame: LucideIcons.Flame,
  Container: LucideIcons.Container,
  CircleDot: LucideIcons.CircleDot,
  Tv: LucideIcons.Tv,
  Shield: LucideIcons.Shield,
  CookingPot: LucideIcons.CookingPot,
  Refrigerator: LucideIcons.Refrigerator,
  Wind: LucideIcons.Wind,
  AirVent: LucideIcons.AirVent,
  Microwave: LucideIcons.Microwave,
  Thermometer: LucideIcons.Thermometer,
  Fan: LucideIcons.Fan,
  Fence: LucideIcons.Fence,
  Dumbbell: LucideIcons.Dumbbell,
  ArrowUpDown: LucideIcons.ArrowUpDown,
  Building: LucideIcons.Building,
  Baby: LucideIcons.Baby,
  TreePine: LucideIcons.TreePine,
  Car: LucideIcons.Car,
  Users: LucideIcons.Users,
  Camera: LucideIcons.Camera,
  Ban: LucideIcons.Ban,
  BadgeCheck: LucideIcons.BadgeCheck,
  Banknote: LucideIcons.Banknote,
  FileSearch: LucideIcons.FileSearch,
  CreditCard: LucideIcons.CreditCard,
  Receipt: LucideIcons.Receipt,
  CalendarDays: LucideIcons.CalendarDays,
  ParkingCircle: LucideIcons.ParkingCircle,
  Footprints: LucideIcons.Footprints,
  Truck: LucideIcons.Truck,
  LayoutGrid: LucideIcons.LayoutGrid,
  Monitor: LucideIcons.Monitor,
  Warehouse: LucideIcons.Warehouse,
  Store: LucideIcons.Store,
  Factory: LucideIcons.Factory,
  Signpost: LucideIcons.Signpost,
  Minus: LucideIcons.Minus,
  Route: LucideIcons.Route,
  Sprout: LucideIcons.Sprout,
  Layers: LucideIcons.Layers,
  Scissors: LucideIcons.Scissors,
  FileCheck: LucideIcons.FileCheck,
  Building2: LucideIcons.Building2,
  UsersRound: LucideIcons.UsersRound,
  TrendingUp: LucideIcons.TrendingUp,
  Heart: LucideIcons.Heart,
  Armchair: LucideIcons.Armchair,
  Briefcase: LucideIcons.Briefcase,
  GraduationCap: LucideIcons.GraduationCap,
  Plane: LucideIcons.Plane,
  Sparkles: LucideIcons.Sparkles,
  ScrollText: LucideIcons.ScrollText,
  MapPin: LucideIcons.MapPin,
  DollarSign: LucideIcons.DollarSign,
  FileText: LucideIcons.FileText,
  Star: LucideIcons.Star,
  Check: LucideIcons.Check,
  X: LucideIcons.X,
  Trees: LucideIcons.Trees,
};

export function DynamicIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = iconMap[name];
  if (!Icon) {
    return <LucideIcons.Circle {...props} />;
  }
  return <Icon {...props} />;
}
